import {
  HttpException,
  HttpStatus,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { CreateProductDto } from './dto/create-product.dto';
import { UpdateProductDto } from './dto/update-product.dto';
import { ProductQueryDto } from './dto/product-query.dto';

@Injectable()
export class ProductsService {
  private products = [
    {
      id: 1,
      name: 'Laptop Pro 15"',
      category: 1,
      description: 'High-performance laptop for professionals',
      quantity: 8,
      price: 1499.99,
      isDiscounted: true,
    },
    {
      id: 2,
      name: 'Wireless Mouse',
      category: 1,
      quantity: 50,
      price: 29.99,
      isDiscounted: false,
    },
    {
      id: 3,
      name: 'Ergonomic Office Chair',
      category: 3,
      description: 'Adjustable lumbar support',
      quantity: 15,
      price: 299.99,
      isDiscounted: true,
    },
    {
      id: 4,
      name: 'Organic Apples (1kg)',
      category: 4,
      quantity: 120,
      price: 4.99,
      isDiscounted: false,
    },
    {
      id: 5,
      name: 'Programming TypeScript Book',
      category: 5,
      description: 'Advanced guide by Boris Cherny',
      quantity: 30,
      price: 45.0,
      isDiscounted: false,
    },
    {
      id: 6,
      name: 'Cinema Ticket',
      category: 6,
      quantity: 200,
      price: 12.5,
      isDiscounted: true,
    },
    {
      id: 7,
      name: 'Taxi Ride Voucher',
      category: 7,
      quantity: 40,
      price: 25.0,
      isDiscounted: false,
    },
    {
      id: 8,
      name: 'Monthly Internet Bill',
      category: 8,
      description: '100 Mbps plan',
      quantity: 1,
      price: 59.99,
      isDiscounted: false,
    },
    {
      id: 9,
      name: 'Restaurant Dinner for Two',
      category: 9,
      quantity: 10,
      price: 120.0,
      isDiscounted: true,
    },
    {
      id: 10,
      name: 'Bluetooth Headphones',
      category: 1,
      description: 'Noise-cancelling',
      quantity: 25,
      price: 199.99,
      isDiscounted: true,
    },
    {
      id: 11,
      name: 'Cotton T-Shirt',
      category: 2,
      quantity: 80,
      price: 19.99,
      isDiscounted: false,
    },
    {
      id: 12,
      name: 'Wooden Desk',
      category: 3,
      description: '140cm wide',
      quantity: 5,
      price: 450.0,
      isDiscounted: false,
    },
    {
      id: 13,
      name: 'Fresh Milk (1L)',
      category: 4,
      quantity: 150,
      price: 1.29,
      isDiscounted: false,
    },
    {
      id: 14,
      name: 'The Great Gatsby',
      category: 5,
      quantity: 60,
      price: 10.99,
      isDiscounted: true,
    },
    {
      id: 15,
      name: 'Concert Ticket - Rock Band',
      category: 6,
      quantity: 50,
      price: 85.0,
      isDiscounted: false,
    },
    {
      id: 16,
      name: 'Bus Monthly Pass',
      category: 7,
      quantity: 30,
      price: 60.0,
      isDiscounted: true,
    },
    {
      id: 17,
      name: 'Electricity Bill',
      category: 8,
      quantity: 1,
      price: 92.45,
      isDiscounted: false,
    },
    {
      id: 18,
      name: 'Pizza Margherita',
      category: 9,
      quantity: 40,
      price: 14.99,
      isDiscounted: false,
    },
    {
      id: 19,
      name: '4K Monitor 27"',
      category: 1,
      quantity: 12,
      price: 399.99,
      isDiscounted: true,
    },
    {
      id: 20,
      name: 'Winter Jacket',
      category: 2,
      description: 'Waterproof',
      quantity: 20,
      price: 129.99,
      isDiscounted: true,
    },
    {
      id: 21,
      name: 'Bookshelf 180cm',
      category: 3,
      quantity: 8,
      price: 179.99,
      isDiscounted: false,
    },
    {
      id: 22,
      name: 'Bananas (1kg)',
      category: 4,
      quantity: 100,
      price: 2.49,
      isDiscounted: false,
    },
    {
      id: 23,
      name: 'Clean Code Book',
      category: 5,
      quantity: 35,
      price: 39.99,
      isDiscounted: false,
    },
    {
      id: 24,
      name: 'Streaming Subscription',
      category: 6,
      quantity: 1,
      price: 14.99,
      isDiscounted: true,
    },
    {
      id: 25,
      name: 'Train Ticket Tbilisi-Batumi',
      category: 7,
      quantity: 25,
      price: 35.0,
      isDiscounted: false,
    },
    {
      id: 26,
      name: 'Water Bill',
      category: 8,
      quantity: 1,
      price: 18.5,
      isDiscounted: false,
    },
    {
      id: 27,
      name: 'Sushi Set',
      category: 9,
      quantity: 15,
      price: 45.0,
      isDiscounted: true,
    },
    {
      id: 28,
      name: 'Mechanical Keyboard',
      category: 1,
      quantity: 18,
      price: 129.99,
      isDiscounted: false,
    },
    {
      id: 29,
      name: 'Jeans Slim Fit',
      category: 2,
      quantity: 45,
      price: 79.99,
      isDiscounted: true,
    },
    {
      id: 30,
      name: 'Coffee Table',
      category: 3,
      quantity: 10,
      price: 89.99,
      isDiscounted: false,
    },
    {
      id: 31,
      name: 'Olive Oil (500ml)',
      category: 4,
      quantity: 70,
      price: 12.99,
      isDiscounted: false,
    },
    {
      id: 32,
      name: 'Dune by Frank Herbert',
      category: 5,
      quantity: 40,
      price: 18.99,
      isDiscounted: false,
    },
    {
      id: 33,
      name: 'Theater Play Ticket',
      category: 6,
      quantity: 60,
      price: 40.0,
      isDiscounted: true,
    },
    {
      id: 34,
      name: 'Uber Ride',
      category: 7,
      quantity: 20,
      price: 18.0,
      isDiscounted: false,
    },
    {
      id: 35,
      name: 'Phone Bill',
      category: 8,
      quantity: 1,
      price: 49.99,
      isDiscounted: false,
    },
    {
      id: 36,
      name: 'Burger Menu',
      category: 9,
      quantity: 80,
      price: 9.99,
      isDiscounted: true,
    },
    {
      id: 37,
      name: 'Smartwatch',
      category: 1,
      quantity: 22,
      price: 299.99,
      isDiscounted: true,
    },
    {
      id: 38,
      name: 'Sneakers',
      category: 2,
      quantity: 55,
      price: 99.99,
      isDiscounted: false,
    },
    {
      id: 39,
      name: 'Sofa 3-Seater',
      category: 3,
      description: 'Fabric upholstery',
      quantity: 4,
      price: 799.99,
      isDiscounted: true,
    },
    {
      id: 40,
      name: 'Rice (5kg)',
      category: 4,
      quantity: 90,
      price: 15.99,
      isDiscounted: false,
    },
    {
      id: 41,
      name: 'Atomic Habits',
      category: 5,
      quantity: 50,
      price: 22.99,
      isDiscounted: false,
    },
    {
      id: 42,
      name: 'Museum Entry',
      category: 6,
      quantity: 100,
      price: 15.0,
      isDiscounted: true,
    },
    {
      id: 43,
      name: 'Gasoline (40L)',
      category: 7,
      quantity: 5,
      price: 70.0,
      isDiscounted: false,
    },
    {
      id: 44,
      name: 'Heating Bill',
      category: 8,
      quantity: 1,
      price: 120.0,
      isDiscounted: false,
    },
    {
      id: 45,
      name: 'Coffee & Pastry',
      category: 9,
      quantity: 150,
      price: 6.5,
      isDiscounted: false,
    },
    {
      id: 46,
      name: 'External SSD 1TB',
      category: 1,
      quantity: 30,
      price: 119.99,
      isDiscounted: true,
    },
    {
      id: 47,
      name: 'Hoodie',
      category: 2,
      quantity: 60,
      price: 49.99,
      isDiscounted: true,
    },
    {
      id: 48,
      name: 'Dining Table',
      category: 3,
      quantity: 6,
      price: 399.99,
      isDiscounted: false,
    },
    {
      id: 49,
      name: 'Tomatoes (1kg)',
      category: 4,
      quantity: 110,
      price: 3.99,
      isDiscounted: false,
    },
    {
      id: 50,
      name: '1984 by George Orwell',
      category: 5,
      quantity: 45,
      price: 14.99,
      isDiscounted: true,
    },
    {
      id: 51,
      name: 'Gym Monthly Membership',
      category: 6,
      quantity: 1,
      price: 55.0,
      isDiscounted: false,
    },
    {
      id: 52,
      name: 'Parking Fee (daily)',
      category: 7,
      quantity: 200,
      price: 8.0,
      isDiscounted: false,
    },
    {
      id: 53,
      name: 'Cable TV Subscription',
      category: 8,
      quantity: 1,
      price: 75.0,
      isDiscounted: false,
    },
    {
      id: 54,
      name: 'Steak Dinner',
      category: 9,
      quantity: 12,
      price: 85.0,
      isDiscounted: true,
    },
    {
      id: 55,
      name: 'Gaming Mouse',
      category: 1,
      quantity: 35,
      price: 79.99,
      isDiscounted: false,
    },
    {
      id: 56,
      name: 'Scarf',
      category: 2,
      quantity: 40,
      price: 24.99,
      isDiscounted: true,
    },
    {
      id: 57,
      name: 'Bed Frame Queen',
      category: 3,
      quantity: 7,
      price: 349.99,
      isDiscounted: false,
    },
    {
      id: 58,
      name: 'Pasta (500g)',
      category: 4,
      quantity: 130,
      price: 2.99,
      isDiscounted: false,
    },
    {
      id: 59,
      name: 'Sapiens by Yuval Noah Harari',
      category: 5,
      quantity: 38,
      price: 19.99,
      isDiscounted: false,
    },
    {
      id: 60,
      name: 'Video Game Download',
      category: 6,
      quantity: 1,
      price: 59.99,
      isDiscounted: true,
    },
    {
      id: 61,
      name: 'Flight Ticket',
      category: 7,
      description: 'One-way economy',
      quantity: 3,
      price: 250.0,
      isDiscounted: true,
    },
    {
      id: 62,
      name: 'Trash Collection Fee',
      category: 8,
      quantity: 1,
      price: 25.0,
      isDiscounted: false,
    },
    {
      id: 63,
      name: 'Ice Cream Tub',
      category: 9,
      quantity: 60,
      price: 7.99,
      isDiscounted: false,
    },
    {
      id: 64,
      name: 'Webcam HD',
      category: 1,
      quantity: 28,
      price: 69.99,
      isDiscounted: true,
    },
    {
      id: 65,
      name: 'Socks Pack (5 pairs)',
      category: 2,
      quantity: 100,
      price: 15.99,
      isDiscounted: false,
    },
    {
      id: 66,
      name: 'Wardrobe',
      category: 3,
      quantity: 5,
      price: 599.99,
      isDiscounted: true,
    },
    {
      id: 67,
      name: 'Bread Loaf',
      category: 4,
      quantity: 200,
      price: 2.5,
      isDiscounted: false,
    },
    {
      id: 68,
      name: 'The Lord of the Rings',
      category: 5,
      quantity: 25,
      price: 39.99,
      isDiscounted: false,
    },
    {
      id: 69,
      name: 'Online Course',
      category: 6,
      quantity: 1,
      price: 99.0,
      isDiscounted: true,
    },
    {
      id: 70,
      name: 'Bike Rental (daily)',
      category: 7,
      quantity: 15,
      price: 20.0,
      isDiscounted: false,
    },
    {
      id: 71,
      name: 'Internet Upgrade Fee',
      category: 8,
      quantity: 1,
      price: 50.0,
      isDiscounted: false,
    },
    {
      id: 72,
      name: 'Sandwich & Drink',
      category: 9,
      quantity: 90,
      price: 8.99,
      isDiscounted: true,
    },
    {
      id: 73,
      name: 'Tablet 10"',
      category: 1,
      quantity: 10,
      price: 399.99,
      isDiscounted: true,
    },
    {
      id: 74,
      name: 'Hat',
      category: 2,
      quantity: 50,
      price: 29.99,
      isDiscounted: false,
    },
    {
      id: 75,
      name: 'Lamp Desk',
      category: 3,
      quantity: 20,
      price: 39.99,
      isDiscounted: false,
    },
    {
      id: 76,
      name: 'Eggs (12 pack)',
      category: 4,
      quantity: 80,
      price: 4.5,
      isDiscounted: false,
    },
    {
      id: 77,
      name: 'Educated by Tara Westover',
      category: 5,
      quantity: 42,
      price: 16.99,
      isDiscounted: true,
    },
    {
      id: 78,
      name: 'Spotify Premium',
      category: 6,
      quantity: 1,
      price: 10.99,
      isDiscounted: false,
    },
    {
      id: 79,
      name: 'Tolls',
      category: 7,
      quantity: 30,
      price: 12.0,
      isDiscounted: false,
    },
    {
      id: 80,
      name: 'Rent (monthly)',
      category: 8,
      quantity: 1,
      price: 1200.0,
      isDiscounted: false,
    },
    {
      id: 81,
      name: 'Fast Food Combo',
      category: 9,
      quantity: 70,
      price: 11.99,
      isDiscounted: true,
    },
    {
      id: 82,
      name: 'Printer Ink Cartridge',
      category: 1,
      quantity: 40,
      price: 45.99,
      isDiscounted: false,
    },
    {
      id: 83,
      name: 'Belt',
      category: 2,
      quantity: 35,
      price: 34.99,
      isDiscounted: true,
    },
    {
      id: 84,
      name: 'Mirror Wall',
      category: 3,
      quantity: 12,
      price: 89.99,
      isDiscounted: false,
    },
    {
      id: 85,
      name: 'Cheese (200g)',
      category: 4,
      quantity: 65,
      price: 6.99,
      isDiscounted: false,
    },
    {
      id: 86,
      name: 'Becoming by Michelle Obama',
      category: 5,
      quantity: 33,
      price: 24.99,
      isDiscounted: true,
    },
    {
      id: 87,
      name: 'Zoo Ticket',
      category: 6,
      quantity: 80,
      price: 20.0,
      isDiscounted: false,
    },
    {
      id: 88,
      name: 'Hotel Night',
      category: 7,
      description: 'Standard room',
      quantity: 2,
      price: 180.0,
      isDiscounted: true,
    },
    {
      id: 89,
      name: 'Insurance Premium',
      category: 8,
      quantity: 1,
      price: 150.0,
      isDiscounted: false,
    },
    {
      id: 90,
      name: 'Smoothie',
      category: 9,
      quantity: 100,
      price: 5.99,
      isDiscounted: false,
    },
    {
      id: 91,
      name: 'Router Wi-Fi 6',
      category: 1,
      quantity: 15,
      price: 149.99,
      isDiscounted: true,
    },
    {
      id: 92,
      name: 'Gloves',
      category: 2,
      quantity: 45,
      price: 19.99,
      isDiscounted: false,
    },
    {
      id: 93,
      name: 'Rug 160x230cm',
      category: 3,
      quantity: 9,
      price: 129.99,
      isDiscounted: true,
    },
    {
      id: 94,
      name: 'Yogurt (4 pack)',
      category: 4,
      quantity: 95,
      price: 4.99,
      isDiscounted: false,
    },
    {
      id: 95,
      name: 'Project Hail Mary',
      category: 5,
      quantity: 28,
      price: 27.99,
      isDiscounted: false,
    },
    {
      id: 96,
      name: 'Netflix Subscription',
      category: 6,
      quantity: 1,
      price: 15.99,
      isDiscounted: true,
    },
    {
      id: 97,
      name: 'Car Rental (day)',
      category: 7,
      quantity: 4,
      price: 80.0,
      isDiscounted: false,
    },
    {
      id: 98,
      name: 'Gym Equipment Maintenance',
      category: 8,
      quantity: 1,
      price: 40.0,
      isDiscounted: false,
    },
    {
      id: 99,
      name: 'Takeout Thai Food',
      category: 9,
      quantity: 25,
      price: 35.0,
      isDiscounted: true,
    },
    {
      id: 100,
      name: 'Smartphone Case',
      category: 1,
      quantity: 75,
      price: 24.99,
      isDiscounted: false,
    },
  ];

  create({ category, name, quantity, price, isDiscounted }: CreateProductDto) {
    if (!category || !name || !quantity || !price || !isDiscounted)
      throw new HttpException('all fild is required', HttpStatus.BAD_REQUEST);
    const lastIndex = this.products[this.products.length - 1]?.id || 0;
    const newExpense = {
      id: lastIndex + 1,
      category: category,
      name: name,
      quantity: quantity,
      price: price,
      isDiscounted: isDiscounted,
    };

    this.products.push(newExpense);
    return newExpense;
  }

  findAll({page,take, isActive, category,priceFrom, priceTo}:ProductQueryDto) {

    const query=this.products
    .filter(o=> 
      (isActive===undefined || o.isDiscounted===isActive) &&
      (category === undefined || o.category === category) &&
      (priceFrom === undefined || o.price >= priceFrom) &&
      (priceTo === undefined || o.price <= priceTo))

    const start = (page-1)*take
    const end= page* take
    return query.slice(start,end);
  }

  findOne(id: number) {
    const expense = this.products.find((e) => e.id === id);
    if (!expense) throw new NotFoundException('product not found');
    return expense;
  }

  update(id: number, { category, name, quantity, price, isDiscounted }: UpdateProductDto) {

    const expenseIndex = this.products.findIndex((e) => e.id === id);
    if (expenseIndex === -1) throw new NotFoundException('product not found');
    const expenseReq = {};
    if (category) expenseReq['category'] = category;
    if (name) expenseReq['productName'] = name;
    if (quantity) expenseReq['quantity'] = quantity;
    if (price) expenseReq['price'] = price;
    if (isDiscounted) expenseReq['isDiscounted'] =isDiscounted;

    this.products[expenseIndex] = {
      ...this.products[expenseIndex],
      ...expenseReq,
    };

    return this.products[expenseIndex];
  }

  remove(id: number) {
    const expenseIndex = this.products.findIndex((e) => e.id === id);
    if (expenseIndex === -1) throw new NotFoundException('product not found');

    const deletedExpense = this.products.splice(expenseIndex, 1);
    return deletedExpense;
  }
}
